const { getDatabase } = require('../src/database');
const path = require('path');

// Данные кормов из Google Sheets (я извлек основные записи из таблицы)
const feedsData = [
  {
    id: 100,
    animal_type: 'собака',
    category: 'терапевтический',
    age_group: 'взрослые собаки мелких пород',
    type: 'сухой',
    brand: 'FORZA10',
    name: 'FORZA10 Active VETdiet MINI/TOY Dog DERMO',
    metabolic_energy: 364.3,
    moisture: 8,
    protein: 23.5,
    fat: 12,
    carbohydrates: 46.1,
    fiber: 2.7,
    ash: 7.7,
    calcium: 1400,
    phosphorus: 1200,
    sodium: 1,
    potassium: 5,
    magnesium: 1800,
    iron: 29.5,
    zinc: 0.38,
    copper: 0.99,
    manganese: 1.49,
    iodine: 2.49,
    selenium: 0.74,
    vitamin_a: 185,
    vitamin_d: 6,
    vitamin_e: 70,
    vitamin_k: 8.5,
    vitamin_b1: 50,
    vitamin_b2: 0.85,
    vitamin_b6: 3.5,
    vitamin_b12: 3,
    ingredients: 'Молотый рис, обезвоженная рыба 17%, рисовые отруби, картофельный крахмал, таблетка AFS – 7% продукта (картофельный белок, минеральные вещества, гидролизованный животный белок рыбы, масло анчоусов, продукты переработки овощей (порошкообразный гель Алоэ вера 0,0112%, мальва 0,0053%), продукты переработки свежих фруктов и овощей (ежевика), свекольный жом, рыбий жир 4%, картофельный белок, масло неочищенных зародышей кукурузы, минеральные вещества, сушеные водоросли (Ascophyllum nodosum), гидролизованный животный белок, маннановые олигосахариды (MOS), фруктолигосахариды (FOS), юкка шидигера.',
    protein_sources: 'Рыба, Картофельный белок'
  },
  {
    id: 101,
    animal_type: 'собака',
    category: 'терапевтический',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'ROYAL CANIN',
    name: 'ROYAL CANIN Hypoallergenic Dog',
    metabolic_energy: 355.0,
    moisture: 8,
    protein: 24.5,
    fat: 11,
    carbohydrates: 47.7,
    fiber: 1.3,
    ash: 8.8,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.5,
    potassium: 0.85,
    magnesium: 800,
    iron: 210,
    zinc: 0.35,
    copper: 20,
    manganese: 75,
    iodine: 3.8,
    selenium: 0.35,
    vitamin_a: 29500,
    vitamin_d: 800,
    vitamin_e: 600,
    vitamin_k: 1.0,
    vitamin_b1: 28.5,
    vitamin_b2: 50,
    vitamin_b6: 78,
    vitamin_b12: 0.15,
    ingredients: 'Гидролизованный соевый белок, рис, животные жиры, картофельный крахмал, растительная клетчатка, гидролизованная печень птицы, свекольный жом, соевое масло, минеральные вещества, фруктоолигосахариды, масло огуречника аптечного.',
    protein_sources: 'Гидролизованный соевый белок'
  },
  {
    id: 102,
    animal_type: 'собака',
    category: 'терапевтический',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'HILL\'S',
    name: 'HILL\'S Prescription Diet z/d Food Sensitivities',
    metabolic_energy: 377.0,
    moisture: 8,
    protein: 20,
    fat: 12.5,
    carbohydrates: 51.4,
    fiber: 1.6,
    ash: 6.5,
    calcium: 690,
    phosphorus: 570,
    sodium: 0.35,
    potassium: 0.75,
    magnesium: 80,
    iron: 190,
    zinc: 0.4,
    copper: 16,
    manganese: 70,
    iodine: 3.5,
    selenium: 0.4,
    vitamin_a: 21000,
    vitamin_d: 700,
    vitamin_e: 670,
    vitamin_k: 0.9,
    vitamin_b1: 30,
    vitamin_b2: 55,
    vitamin_b6: 85,
    vitamin_b12: 0.16,
    ingredients: 'Гидролизованный белок курицы, кукурузный крахмал, соевое масло, целлюлоза, минеральные вещества, DL-метионин, карбонат кальция, витамины, таурин, микроэлементы, бета-каротин.',
    protein_sources: 'Гидролизованный белок курицы'
  },
  {
    id: 103,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки крупных пород',
    type: 'сухой',
    brand: 'ACANA',
    name: 'ACANA Adult Large Breed',
    metabolic_energy: 338.0,
    moisture: 12,
    protein: 31,
    fat: 15,
    carbohydrates: 25,
    fiber: 5,
    ash: 7,
    calcium: 1200,
    phosphorus: 1000,
    sodium: 0.3,
    potassium: 0.7,
    magnesium: 900,
    iron: 80,
    zinc: 0.15,
    copper: 11,
    manganese: 15,
    iodine: 2.3,
    selenium: 0.3,
    vitamin_a: 15000,
    vitamin_d: 2000,
    vitamin_e: 150,
    vitamin_k: 0.5,
    vitamin_b1: 25,
    vitamin_b2: 16,
    vitamin_b6: 20,
    vitamin_b12: 0.1,
    ingredients: 'Свежее мясо цыпленка (18%), дегидрированное мясо цыпленка (18%), дегидрированное мясо индейки (6%), красная чечевица, цельный зеленый горошек, куриный жир (5%), свежие куриные яйца (4%), свежая камбала (4%), куриная печень (3%), свежее мясо индейки (3%), свежая печень индейки (3%), свежее сердце индейки (3%), свежий хрящ цыпленка (3%), дегидрированная сельдь (3%), дегидрированная сардина (3%), дегидрированная скумбрия (3%).',
    protein_sources: 'Курица, Индейка, Рыба, Яйца'
  },
  {
    id: 104,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки мелких пород',
    type: 'сухой',
    brand: 'ORIJEN',
    name: 'ORIJEN Small Breed',
    metabolic_energy: 394.0,
    moisture: 10,
    protein: 38,
    fat: 18,
    carbohydrates: 20,
    fiber: 5,
    ash: 9,
    calcium: 1400,
    phosphorus: 1100,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 1000,
    iron: 200,
    zinc: 0.18,
    copper: 20,
    manganese: 18,
    iodine: 2.8,
    selenium: 0.4,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 120,
    vitamin_k: 0.7,
    vitamin_b1: 12,
    vitamin_b2: 16,
    vitamin_b6: 10,
    vitamin_b12: 0.15,
    ingredients: 'Свежее мясо цыпленка (13%), свежее мясо индейки (7%), свежие яйца (7%), свежая печень цыпленка (6%), свежая камбала (5%), свежая печень индейки (5%), свежее сердце цыпленка (5%), свежее сердце индейки (5%), свежая шея индейки (4%), дегидрированное мясо цыпленка (4%), дегидрированное мясо индейки (4%), дегидрированная макрель (4%), дегидрированная сардина (4%), дегидрированная сельдь (4%).',
    protein_sources: 'Курица, Индейка, Рыба, Яйца'
  },
  {
    id: 105,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'ROYAL CANIN',
    name: 'ROYAL CANIN Indoor Adult',
    metabolic_energy: 375.0,
    moisture: 8,
    protein: 27,
    fat: 13,
    carbohydrates: 39.5,
    fiber: 6.1,
    ash: 6.4,
    calcium: 1000,
    phosphorus: 850,
    sodium: 0.5,
    potassium: 0.8,
    magnesium: 800,
    iron: 165,
    zinc: 0.2,
    copper: 15,
    manganese: 60,
    iodine: 4.8,
    selenium: 0.26,
    vitamin_a: 25000,
    vitamin_d: 1000,
    vitamin_e: 500,
    vitamin_k: 0.6,
    vitamin_b1: 27.4,
    vitamin_b2: 49.6,
    vitamin_b6: 76.3,
    vitamin_b12: 0.14,
    ingredients: 'Дегидрированное мясо птицы, рис, пшеница, изолят растительных белков, животные жиры, гидролизат белков животного происхождения, растительная клетчатка, свекольный жом, минеральные вещества, соевое масло, фруктоолигосахариды, дрожжи.',
    protein_sources: 'Птица'
  },
  {
    id: 106,
    animal_type: 'кошка',
    category: 'терапевтический',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'HILL\'S',
    name: 'HILL\'S Prescription Diet c/d Multicare Urinary Care',
    metabolic_energy: 395.0,
    moisture: 8,
    protein: 32,
    fat: 15.5,
    carbohydrates: 34.8,
    fiber: 2.3,
    ash: 7.4,
    calcium: 800,
    phosphorus: 650,
    sodium: 0.9,
    potassium: 0.8,
    magnesium: 650,
    iron: 160,
    zinc: 0.16,
    copper: 7.4,
    manganese: 7.1,
    iodine: 1.4,
    selenium: 0.2,
    vitamin_a: 21645,
    vitamin_d: 730,
    vitamin_e: 550,
    vitamin_k: 0.8,
    vitamin_b1: 16.9,
    vitamin_b2: 19.1,
    vitamin_b6: 25.4,
    vitamin_b12: 0.07,
    ingredients: 'Мука из мяса курицы, кукуруза, пшеничная клейковина, животный жир, мука из кукурузной клейковины, целлюлоза, куриная печень, молочная кислота, хлорид калия, соль йодированная, таурин, витамины, L-карнитин, микроэлементы, бета-каротин.',
    protein_sources: 'Курица'
  },
  {
    id: 107,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'щенки крупных пород',
    type: 'сухой',
    brand: 'PURINA PRO PLAN',
    name: 'PURINA PRO PLAN Large Puppy with OPTISTART',
    metabolic_energy: 405.0,
    moisture: 8,
    protein: 28,
    fat: 16,
    carbohydrates: 36,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.4,
    potassium: 0.7,
    magnesium: 900,
    iron: 100,
    zinc: 0.15,
    copper: 10,
    manganese: 40,
    iodine: 1.5,
    selenium: 0.15,
    vitamin_a: 30000,
    vitamin_d: 1700,
    vitamin_e: 460,
    vitamin_k: 1.3,
    vitamin_b1: 15,
    vitamin_b2: 14,
    vitamin_b6: 8,
    vitamin_b12: 0.14,
    ingredients: 'Курица (20%), дегидрированные белки птицы, рис, пшеничная клейковина, кукуруза, животные жиры, сухая свекольная мякоть, минеральные вещества, рыбий жир, яичный порошок, дрожжи.',
    protein_sources: 'Курица'
  },
  {
    id: 108,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'котята',
    type: 'сухой',
    brand: 'WHISKAS',
    name: 'WHISKAS Kitten',
    metabolic_energy: 415.0,
    moisture: 8,
    protein: 36,
    fat: 16,
    carbohydrates: 28,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1300,
    phosphorus: 1100,
    sodium: 0.6,
    potassium: 0.8,
    magnesium: 850,
    iron: 75,
    zinc: 0.14,
    copper: 5,
    manganese: 20,
    iodine: 2.3,
    selenium: 0.18,
    vitamin_a: 12000,
    vitamin_d: 1200,
    vitamin_e: 120,
    vitamin_k: 0.5,
    vitamin_b1: 10,
    vitamin_b2: 10,
    vitamin_b6: 4,
    vitamin_b12: 0.09,
    ingredients: 'Злаки, мясо и продукты переработки мяса (в т.ч. курица минимум 4%), растительные белковые экстракты, масла и жиры, овощи, минеральные вещества, дрожжи, витамины, антиоксиданты.',
    protein_sources: 'Курица, Мясо'
  },
  {
    id: 109,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'пожилые собаки',
    type: 'сухой',
    brand: 'EUKANUBA',
    name: 'EUKANUBA Senior Medium Breed',
    metabolic_energy: 365.0,
    moisture: 8,
    protein: 25,
    fat: 13,
    carbohydrates: 42,
    fiber: 3.8,
    ash: 8.2,
    calcium: 1000,
    phosphorus: 800,
    sodium: 0.35,
    potassium: 0.7,
    magnesium: 750,
    iron: 180,
    zinc: 0.2,
    copper: 18,
    manganese: 56,
    iodine: 3.1,
    selenium: 0.4,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 250,
    vitamin_k: 0.75,
    vitamin_b1: 22,
    vitamin_b2: 8.8,
    vitamin_b6: 7.5,
    vitamin_b12: 0.05,
    ingredients: 'Дегидрированное мясо птицы, пшеница, кукуруза, ячмень, животные жиры, сухая свекольная мякоть, минеральные вещества, гидролизованный белок, рыбий жир, маннановые олигосахариды, фруктоолигосахариды.',
    protein_sources: 'Птица'
  },
  {
    id: 110,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'BRIT PREMIUM',
    name: 'BRIT PREMIUM Adult Large',
    metabolic_energy: 375.0,
    moisture: 10,
    protein: 24,
    fat: 12,
    carbohydrates: 43,
    fiber: 2.5,
    ash: 8.5,
    calcium: 1300,
    phosphorus: 1000,
    sodium: 0.3,
    potassium: 0.6,
    magnesium: 900,
    iron: 85,
    zinc: 0.12,
    copper: 12,
    manganese: 35,
    iodine: 2.2,
    selenium: 0.25,
    vitamin_a: 20000,
    vitamin_d: 1800,
    vitamin_e: 400,
    vitamin_k: 0.6,
    vitamin_b1: 12,
    vitamin_b2: 20,
    vitamin_b6: 6,
    vitamin_b12: 0.05,
    ingredients: 'Курица (25%), рис (18%), кукуруза, куриный жир, сушеные яблоки, лососевый жир, пивные дрожжи, натуральные ароматизаторы, сушеная морковь, глюкозамин, хондроитин сульфат.',
    protein_sources: 'Курица, Лосось'
  },
  {
    id: 111,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'BRIT PREMIUM',
    name: 'BRIT PREMIUM Cat Adult Chicken',
    metabolic_energy: 395.0,
    moisture: 10,
    protein: 36,
    fat: 15,
    carbohydrates: 25,
    fiber: 2.0,
    ash: 7.0,
    calcium: 1000,
    phosphorus: 900,
    sodium: 0.4,
    potassium: 0.7,
    magnesium: 750,
    iron: 100,
    zinc: 0.15,
    copper: 15,
    manganese: 25,
    iodine: 2.5,
    selenium: 0.3,
    vitamin_a: 25000,
    vitamin_d: 1600,
    vitamin_e: 250,
    vitamin_k: 0.5,
    vitamin_b1: 10,
    vitamin_b2: 15,
    vitamin_b6: 8,
    vitamin_b12: 0.08,
    ingredients: 'Дегидрированная курица (25%), рис (18%), куриный жир, кукурузная глютен, сушёные яблоки, куриная печень, лососевый жир, пивные дрожжи, сушёная морковь, таурин.',
    protein_sources: 'Курица, Лосось'
  },
  {
    id: 112,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'щенки средних пород',
    type: 'сухой',
    brand: 'FARMINA',
    name: 'FARMINA N&D Grain Free Puppy Medium Chicken & Pomegranate',
    metabolic_energy: 420.0,
    moisture: 8,
    protein: 35,
    fat: 20,
    carbohydrates: 20,
    fiber: 2.9,
    ash: 8.5,
    calcium: 1500,
    phosphorus: 1300,
    sodium: 0.4,
    potassium: 0.9,
    magnesium: 1000,
    iron: 120,
    zinc: 0.16,
    copper: 13,
    manganese: 40,
    iodine: 1.8,
    selenium: 0.4,
    vitamin_a: 18000,
    vitamin_d: 1200,
    vitamin_e: 600,
    vitamin_k: 1.2,
    vitamin_b1: 10,
    vitamin_b2: 13,
    vitamin_b6: 8.1,
    vitamin_b12: 0.1,
    ingredients: 'Свежее мясо курицы (20%), дегидрированное мясо курицы (20%), картофель, куриный жир, дегидрированные цельные яйца, сельдь, дегидрированная сельдь, гранат (2.5%), шпинат, морковь, яблоки.',
    protein_sources: 'Курица, Яйца, Сельдь'
  },
  {
    id: 113,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'FARMINA',
    name: 'FARMINA N&D Grain Free Adult Cat Chicken & Pomegranate',
    metabolic_energy: 395.0,
    moisture: 8,
    protein: 44,
    fat: 20,
    carbohydrates: 15,
    fiber: 1.8,
    ash: 8.0,
    calcium: 1200,
    phosphorus: 1100,
    sodium: 0.4,
    potassium: 0.9,
    magnesium: 800,
    iron: 80,
    zinc: 0.15,
    copper: 15,
    manganese: 48,
    iodine: 1.5,
    selenium: 0.3,
    vitamin_a: 18000,
    vitamin_d: 1200,
    vitamin_e: 600,
    vitamin_k: 1.2,
    vitamin_b1: 12,
    vitamin_b2: 14,
    vitamin_b6: 8.1,
    vitamin_b12: 0.1,
    ingredients: 'Свежее мясо курицы (20%), дегидрированное мясо курицы (20%), картофель, куриный жир, дегидрированные цельные яйца, сельдь, дегидрированная сельдь, гранат (2.5%), шпинат, морковь, яблоки, таурин.',
    protein_sources: 'Курица, Яйца, Сельдь'
  },
  {
    id: 114,
    animal_type: 'собака',
    category: 'терапевтический',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'ROYAL CANIN',
    name: 'ROYAL CANIN Digestive Care',
    metabolic_energy: 360.0,
    moisture: 8,
    protein: 23,
    fat: 12,
    carbohydrates: 47,
    fiber: 1.9,
    ash: 7.1,
    calcium: 1000,
    phosphorus: 800,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 700,
    iron: 160,
    zinc: 0.2,
    copper: 15,
    manganese: 64,
    iodine: 3.0,
    selenium: 0.31,
    vitamin_a: 25500,
    vitamin_d: 800,
    vitamin_e: 500,
    vitamin_k: 0.9,
    vitamin_b1: 24,
    vitamin_b2: 44,
    vitamin_b6: 70,
    vitamin_b12: 0.13,
    ingredients: 'Рис, дегидрированное мясо птицы, животные жиры, изолят растительных белков, кукуруза, свекольный жом, минеральные вещества, рыбий жир, соевое масло, фруктоолигосахариды.',
    protein_sources: 'Птица'
  },
  {
    id: 115,
    animal_type: 'кошка',
    category: 'терапевтический',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'ROYAL CANIN',
    name: 'ROYAL CANIN Digestive Care Cat',
    metabolic_energy: 385.0,
    moisture: 8,
    protein: 32,
    fat: 16,
    carbohydrates: 30,
    fiber: 1.5,
    ash: 7.5,
    calcium: 1000,
    phosphorus: 900,
    sodium: 0.5,
    potassium: 0.8,
    magnesium: 700,
    iron: 165,
    zinc: 0.2,
    copper: 15,
    manganese: 60,
    iodine: 4.8,
    selenium: 0.26,
    vitamin_a: 25000,
    vitamin_d: 1000,
    vitamin_e: 500,
    vitamin_k: 0.6,
    vitamin_b1: 27.4,
    vitamin_b2: 49.6,
    vitamin_b6: 76.3,
    vitamin_b12: 0.14,
    ingredients: 'Дегидрированное мясо птицы, рис, изолят растительных белков, животные жиры, кукурузная глютен, свекольный жом, минеральные вещества, рыбий жир, таурин.',
    protein_sources: 'Птица'
  },
  {
    id: 116,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки мелких пород',
    type: 'сухой',
    brand: 'CANAGAN',
    name: 'CANAGAN Free Range Chicken Small Breed',
    metabolic_energy: 385.0,
    moisture: 9,
    protein: 33,
    fat: 17,
    carbohydrates: 29,
    fiber: 3.0,
    ash: 9.0,
    calcium: 1800,
    phosphorus: 1300,
    sodium: 0.2,
    potassium: 0.6,
    magnesium: 1100,
    iron: 120,
    zinc: 0.1,
    copper: 20,
    manganese: 35,
    iodine: 2.0,
    selenium: 0.3,
    vitamin_a: 16650,
    vitamin_d: 2000,
    vitamin_e: 240,
    vitamin_k: 0.5,
    vitamin_b1: 12,
    vitamin_b2: 18,
    vitamin_b6: 6,
    vitamin_b12: 0.05,
    ingredients: 'Свежая курица на свободном выгуле (26%), дегидрированная курица (25%), сладкий картофель, горох, картофель, горошек, люцерна, куриный жир (2.9%), дегидрированное яйцо (2.5%), куриный бульон (1.5%).',
    protein_sources: 'Курица, Яйца'
  },
  {
    id: 117,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'CANAGAN',
    name: 'CANAGAN Free Range Chicken Cat',
    metabolic_energy: 390.0,
    moisture: 9,
    protein: 37,
    fat: 20,
    carbohydrates: 20,
    fiber: 1.5,
    ash: 8.5,
    calcium: 1500,
    phosphorus: 1100,
    sodium: 0.25,
    potassium: 0.7,
    magnesium: 800,
    iron: 15,
    zinc: 0.1,
    copper: 10,
    manganese: 35,
    iodine: 2.2,
    selenium: 0.3,
    vitamin_a: 25000,
    vitamin_d: 1750,
    vitamin_e: 320,
    vitamin_k: 0.5,
    vitamin_b1: 15,
    vitamin_b2: 20,
    vitamin_b6: 8,
    vitamin_b12: 0.1,
    ingredients: 'Свежая курица на свободном выгуле (26%), дегидрированная курица (25%), сладкий картофель, картофель, горох, куриный жир (4.2%), люцерна, дегидрированное яйцо (3.5%), куриный бульон (1.5%), таурин.',
    protein_sources: 'Курица, Яйца'
  },
  {
    id: 118,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'щенки мелких пород',
    type: 'сухой',
    brand: 'WELLNESS CORE',
    name: 'WELLNESS CORE Puppy Small Breed Turkey & Chicken',
    metabolic_energy: 415.0,
    moisture: 10,
    protein: 36,
    fat: 18,
    carbohydrates: 25,
    fiber: 4.0,
    ash: 7.0,
    calcium: 1600,
    phosphorus: 1200,
    sodium: 0.25,
    potassium: 0.75,
    magnesium: 1200,
    iron: 80,
    zinc: 0.15,
    copper: 15,
    manganese: 25,
    iodine: 1.5,
    selenium: 0.35,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 150,
    vitamin_k: 0.8,
    vitamin_b1: 25,
    vitamin_b2: 5.0,
    vitamin_b6: 4.0,
    vitamin_b12: 0.1,
    ingredients: 'Дегидрированная индейка, дегидрированная курица, горох, чечевица, куриный жир, томатные выжимки, куриная печень, лососевый жир, шпинат, брокколи, морковь, петрушка, яблоки, черника.',
    protein_sources: 'Индейка, Курица, Лосось'
  },
  {
    id: 119,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'котята',
    type: 'сухой',
    brand: 'WELLNESS CORE',
    name: 'WELLNESS CORE Kitten Turkey & Chicken',
    metabolic_energy: 440.0,
    moisture: 10,
    protein: 45,
    fat: 18,
    carbohydrates: 15,
    fiber: 3.0,
    ash: 9.0,
    calcium: 1800,
    phosphorus: 1400,
    sodium: 0.3,
    potassium: 0.8,
    magnesium: 1000,
    iron: 90,
    zinc: 0.18,
    copper: 18,
    manganese: 35,
    iodine: 2.5,
    selenium: 0.4,
    vitamin_a: 30000,
    vitamin_d: 2000,
    vitamin_e: 200,
    vitamin_k: 1.0,
    vitamin_b1: 30,
    vitamin_b2: 8.0,
    vitamin_b6: 6.0,
    vitamin_b12: 0.15,
    ingredients: 'Дегидрированная индейка, дегидрированная курица, горох, куриный жир, томатные выжимки, куриная печень, лососевый жир, шпинат, брокколи, морковь, таурин, петрушка, яблоки, черника.',
    protein_sources: 'Индейка, Курица, Лосось'
  },
  {
    id: 120,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'TASTE OF THE WILD',
    name: 'TASTE OF THE WILD High Prairie Adult',
    metabolic_energy: 370.0,
    moisture: 10,
    protein: 32,
    fat: 18,
    carbohydrates: 30,
    fiber: 4.0,
    ash: 6.0,
    calcium: 1200,
    phosphorus: 1000,
    sodium: 0.16,
    potassium: 0.8,
    magnesium: 1300,
    iron: 120,
    zinc: 0.15,
    copper: 12,
    manganese: 48,
    iodine: 1.5,
    selenium: 0.35,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 150,
    vitamin_k: 0.8,
    vitamin_b1: 36,
    vitamin_b2: 15.6,
    vitamin_b6: 4.2,
    vitamin_b12: 0.112,
    ingredients: 'Буйвол, мука из баранины, сладкий картофель, горох, картофель, масло канолы, мука из океанической рыбы, жареные бизоньи кости, жареная оленина, говяжий белок.',
    protein_sources: 'Буйвол, Баранина, Рыба, Бизон, Оленина'
  },
  {
    id: 121,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'TASTE OF THE WILD',
    name: 'TASTE OF THE WILD Canyon River Feline',
    metabolic_energy: 385.0,
    moisture: 10,
    protein: 42,
    fat: 18,
    carbohydrates: 20,
    fiber: 3.0,
    ash: 7.0,
    calcium: 1200,
    phosphorus: 1000,
    sodium: 0.35,
    potassium: 0.8,
    magnesium: 900,
    iron: 80,
    zinc: 0.15,
    copper: 10,
    manganese: 48,
    iodine: 1.5,
    selenium: 0.3,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 150,
    vitamin_k: 0.8,
    vitamin_b1: 36,
    vitamin_b2: 15.6,
    vitamin_b6: 4.2,
    vitamin_b12: 0.112,
    ingredients: 'Форель, лососевая мука, сладкий картофель, горох, картофель, масло канолы, копченый лосось, куриная печень, натуральный ароматизатор, океаническая рыбная мука, таурин.',
    protein_sources: 'Форель, Лосось, Курица'
  },
  {
    id: 122,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки мелких пород',
    type: 'сухой',
    brand: 'APPLAWS',
    name: 'APPLAWS Adult Small & Medium Breed Chicken',
    metabolic_energy: 350.0,
    moisture: 8,
    protein: 28,
    fat: 14,
    carbohydrates: 38,
    fiber: 4.0,
    ash: 8.0,
    calcium: 1400,
    phosphorus: 1100,
    sodium: 0.3,
    potassium: 0.7,
    magnesium: 1200,
    iron: 120,
    zinc: 0.12,
    copper: 15,
    manganese: 25,
    iodine: 2.0,
    selenium: 0.25,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 200,
    vitamin_k: 0.6,
    vitamin_b1: 15,
    vitamin_b2: 12,
    vitamin_b6: 8,
    vitamin_b12: 0.06,
    ingredients: 'Дегидрированная курица (65%), сладкий картофель, свекольная мякоть, куриный бульон, куриный жир, минералы, витамины, клюква, яблоки, морковь, шпинат, тыква, мята, инулин.',
    protein_sources: 'Курица'
  },
  {
    id: 123,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'APPLAWS',
    name: 'APPLAWS Adult Cat Chicken',
    metabolic_energy: 390.0,
    moisture: 8,
    protein: 37,
    fat: 20,
    carbohydrates: 25,
    fiber: 2.5,
    ash: 7.5,
    calcium: 1300,
    phosphorus: 1000,
    sodium: 0.35,
    potassium: 0.8,
    magnesium: 900,
    iron: 90,
    zinc: 0.15,
    copper: 12,
    manganese: 30,
    iodine: 2.2,
    selenium: 0.3,
    vitamin_a: 20000,
    vitamin_d: 1800,
    vitamin_e: 250,
    vitamin_k: 0.7,
    vitamin_b1: 18,
    vitamin_b2: 15,
    vitamin_b6: 10,
    vitamin_b12: 0.08,
    ingredients: 'Дегидрированная курица (75%), сладкий картофель, куриный жир, куриный бульон, свекольная мякоть, минералы, витамины, клюква, таурин, DL-метионин.',
    protein_sources: 'Курица'
  },
  {
    id: 124,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'щенки всех пород',
    type: 'сухой',
    brand: 'BRIT CARE',
    name: 'BRIT CARE Puppy All Breed Lamb & Rice',
    metabolic_energy: 405.0,
    moisture: 10,
    protein: 30,
    fat: 16,
    carbohydrates: 32,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1600,
    phosphorus: 1200,
    sodium: 0.3,
    potassium: 0.8,
    magnesium: 1100,
    iron: 110,
    zinc: 0.16,
    copper: 18,
    manganese: 40,
    iodine: 2.0,
    selenium: 0.4,
    vitamin_a: 25000,
    vitamin_d: 1800,
    vitamin_e: 350,
    vitamin_k: 0.8,
    vitamin_b1: 15,
    vitamin_b2: 18,
    vitamin_b6: 9,
    vitamin_b12: 0.1,
    ingredients: 'Баранина (22%), рис (20%), куриный жир, сушеные яблоки, натуральные ароматизаторы, лососевый жир, пивные дрожжи, сушеная морковь, глюкозамин, хондроитин сульфат.',
    protein_sources: 'Баранина, Лосось'
  },
  {
    id: 125,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'котята',
    type: 'сухой',
    brand: 'BRIT CARE',
    name: 'BRIT CARE Kitten Chicken & Rice',
    metabolic_energy: 425.0,
    moisture: 10,
    protein: 40,
    fat: 20,
    carbohydrates: 18,
    fiber: 2.0,
    ash: 10.0,
    calcium: 1800,
    phosphorus: 1400,
    sodium: 0.4,
    potassium: 0.9,
    magnesium: 1000,
    iron: 100,
    zinc: 0.18,
    copper: 20,
    manganese: 45,
    iodine: 2.8,
    selenium: 0.4,
    vitamin_a: 30000,
    vitamin_d: 2000,
    vitamin_e: 400,
    vitamin_k: 1.0,
    vitamin_b1: 18,
    vitamin_b2: 20,
    vitamin_b6: 12,
    vitamin_b12: 0.12,
    ingredients: 'Курица (25%), рис (18%), куриный жир, сушеные яблоки, натуральные ароматизаторы, лососевый жир, таурин, пивные дрожжи, сушеная морковь, витамины, минералы.',
    protein_sources: 'Курица, Лосось'
  },
  {
    id: 126,
    animal_type: 'собака',
    category: 'терапевтический',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'HILLS',
    name: 'HILLS Prescription Diet w/d Weight Management',
    metabolic_energy: 315.0,
    moisture: 8,
    protein: 18,
    fat: 8,
    carbohydrates: 55,
    fiber: 15.0,
    ash: 6.0,
    calcium: 800,
    phosphorus: 600,
    sodium: 0.3,
    potassium: 0.7,
    magnesium: 600,
    iron: 150,
    zinc: 0.18,
    copper: 12,
    manganese: 45,
    iodine: 2.5,
    selenium: 0.35,
    vitamin_a: 20000,
    vitamin_d: 1500,
    vitamin_e: 400,
    vitamin_k: 0.8,
    vitamin_b1: 25,
    vitamin_b2: 15,
    vitamin_b6: 12,
    vitamin_b12: 0.08,
    ingredients: 'Кукуруза, куриная мука, целлюлоза, куриный жир, свекольная мякоть, льняное семя, карбонат кальция, соль, витамины, минералы, антиоксиданты.',
    protein_sources: 'Курица'
  },
  {
    id: 127,
    animal_type: 'кошка',
    category: 'терапевтический',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'HILLS',
    name: 'HILLS Prescription Diet r/d Weight Reduction',
    metabolic_energy: 325.0,
    moisture: 8,
    protein: 35,
    fat: 8.5,
    carbohydrates: 35,
    fiber: 12.0,
    ash: 6.5,
    calcium: 900,
    phosphorus: 700,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 650,
    iron: 160,
    zinc: 0.2,
    copper: 15,
    manganese: 50,
    iodine: 3.0,
    selenium: 0.3,
    vitamin_a: 22000,
    vitamin_d: 1600,
    vitamin_e: 450,
    vitamin_k: 0.9,
    vitamin_b1: 28,
    vitamin_b2: 18,
    vitamin_b6: 15,
    vitamin_b12: 0.09,
    ingredients: 'Куриная мука, кукурузная глютен, целлюлоза, кукуруза, куриный жир, свекольная мякоть, таурин, L-карнитин, витамины, минералы.',
    protein_sources: 'Курица'
  },
  {
    id: 128,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'HAPPY DOG',
    name: 'HAPPY DOG Supreme Sensible Canada',
    metabolic_energy: 360.0,
    moisture: 9,
    protein: 24.5,
    fat: 10.5,
    carbohydrates: 45,
    fiber: 3.0,
    ash: 8.0,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.35,
    potassium: 0.6,
    magnesium: 800,
    iron: 120,
    zinc: 0.14,
    copper: 16,
    manganese: 40,
    iodine: 2.2,
    selenium: 0.25,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 180,
    vitamin_k: 0.6,
    vitamin_b1: 15,
    vitamin_b2: 14,
    vitamin_b6: 8,
    vitamin_b12: 0.07,
    ingredients: 'Лосось (25%), картофельные хлопья, морская рыба, картофельный белок, рапсовое масло, свекольная мякоть, яблочная мякоть, дрожжи, новозеландский моллюск.',
    protein_sources: 'Лосось, Морская рыба'
  },
  {
    id: 129,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'HAPPY CAT',
    name: 'HAPPY CAT Supreme Adult Atlantic Salmon',
    metabolic_energy: 385.0,
    moisture: 8,
    protein: 32,
    fat: 18,
    carbohydrates: 30,
    fiber: 2.5,
    ash: 7.5,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 750,
    iron: 120,
    zinc: 0.15,
    copper: 15,
    manganese: 45,
    iodine: 2.5,
    selenium: 0.3,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 180,
    vitamin_k: 0.6,
    vitamin_b1: 15,
    vitamin_b2: 14,
    vitamin_b6: 8,
    vitamin_b12: 0.07,
    ingredients: 'Птица (22%), рис, кукуруза, птичий жир, лосось (8%), свекольная мякоть, яблочная мякоть, дрожжи, хлорид натрия, таурин.',
    protein_sources: 'Птица, Лосось'
  },
  {
    id: 130,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'пожилые собаки',
    type: 'сухой',
    brand: 'MONGE',
    name: 'MONGE Dog Senior',
    metabolic_energy: 355.0,
    moisture: 8,
    protein: 24,
    fat: 12,
    carbohydrates: 44,
    fiber: 3.5,
    ash: 8.5,
    calcium: 1000,
    phosphorus: 800,
    sodium: 0.3,
    potassium: 0.7,
    magnesium: 700,
    iron: 160,
    zinc: 0.18,
    copper: 16,
    manganese: 50,
    iodine: 2.8,
    selenium: 0.35,
    vitamin_a: 20000,
    vitamin_d: 1600,
    vitamin_e: 300,
    vitamin_k: 0.8,
    vitamin_b1: 20,
    vitamin_b2: 16,
    vitamin_b6: 10,
    vitamin_b12: 0.08,
    ingredients: 'Курица (28%), рис (26%), кукуруза, куриный жир, свекольная мякоть, рыбий жир, дрожжи, глюкозамин, хондроитин, витамины, минералы.',
    protein_sources: 'Курица, Рыба'
  },
  {
    id: 131,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'MONGE',
    name: 'MONGE Cat Adult Chicken',
    metabolic_energy: 380.0,
    moisture: 8,
    protein: 32,
    fat: 16,
    carbohydrates: 32,
    fiber: 2.8,
    ash: 9.2,
    calcium: 1000,
    phosphorus: 850,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 750,
    iron: 150,
    zinc: 0.15,
    copper: 15,
    manganese: 45,
    iodine: 2.3,
    selenium: 0.3,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 200,
    vitamin_k: 0.7,
    vitamin_b1: 16,
    vitamin_b2: 15,
    vitamin_b6: 9,
    vitamin_b12: 0.08,
    ingredients: 'Курица (32%), рис, кукуруза, куриный жир, свекольная мякоть, рыбий жир, таурин, дрожжи, витамины, минералы.',
    protein_sources: 'Курица, Рыба'
  },
  {
    id: 132,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'TRAINER',
    name: 'TRAINER Natural Adult Medium/Maxi Chicken & Rice',
    metabolic_energy: 370.0,
    moisture: 8,
    protein: 26,
    fat: 14,
    carbohydrates: 40,
    fiber: 3.5,
    ash: 8.5,
    calcium: 1200,
    phosphorus: 950,
    sodium: 0.35,
    potassium: 0.7,
    magnesium: 850,
    iron: 140,
    zinc: 0.14,
    copper: 16,
    manganese: 42,
    iodine: 2.1,
    selenium: 0.28,
    vitamin_a: 16000,
    vitamin_d: 1600,
    vitamin_e: 190,
    vitamin_k: 0.65,
    vitamin_b1: 14,
    vitamin_b2: 13,
    vitamin_b6: 7.5,
    vitamin_b12: 0.065,
    ingredients: 'Свежая курица (15%), дегидрированная курица (15%), рис (10%), кукуруза, куриный жир, овес, свекольная мякоть, пивные дрожжи, льняное семя.',
    protein_sources: 'Курица'
  },
  {
    id: 133,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'TRAINER',
    name: 'TRAINER Natural Cat Adult Tuna',
    metabolic_energy: 395.0,
    moisture: 8,
    protein: 35,
    fat: 17,
    carbohydrates: 28,
    fiber: 2.2,
    ash: 7.8,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 800,
    iron: 130,
    zinc: 0.14,
    copper: 14,
    manganese: 40,
    iodine: 2.2,
    selenium: 0.25,
    vitamin_a: 16000,
    vitamin_d: 1600,
    vitamin_e: 190,
    vitamin_k: 0.65,
    vitamin_b1: 14,
    vitamin_b2: 13,
    vitamin_b6: 7.5,
    vitamin_b12: 0.065,
    ingredients: 'Тунец (20%), дегидрированная рыба (18%), рис, кукуруза, куриный жир, овес, свекольная мякоть, таурин, пивные дрожжи.',
    protein_sources: 'Тунец, Рыба'
  },
  {
    id: 134,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'щенки крупных пород',
    type: 'сухой',
    brand: 'ALMO NATURE',
    name: 'ALMO NATURE Holistic Puppy Large Chicken & Rice',
    metabolic_energy: 385.0,
    moisture: 8.5,
    protein: 30,
    fat: 14,
    carbohydrates: 37,
    fiber: 2.5,
    ash: 8.0,
    calcium: 1400,
    phosphorus: 1100,
    sodium: 0.25,
    potassium: 0.65,
    magnesium: 950,
    iron: 130,
    zinc: 0.13,
    copper: 15,
    manganese: 38,
    iodine: 1.9,
    selenium: 0.22,
    vitamin_a: 26000,
    vitamin_d: 1800,
    vitamin_e: 300,
    vitamin_k: 0.8,
    vitamin_b1: 12,
    vitamin_b2: 20,
    vitamin_b6: 8,
    vitamin_b12: 0.1,
    ingredients: 'Свежая курица (26%), дегидрированная курица (14%), рис (14%), овес, куриный жир, свекольная мякоть, дрожжи, минералы.',
    protein_sources: 'Курица'
  },
  {
    id: 135,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'котята',
    type: 'сухой',
    brand: 'ALMO NATURE',
    name: 'ALMO NATURE Holistic Kitten Chicken & Rice',
    metabolic_energy: 405.0,
    moisture: 8.5,
    protein: 32,
    fat: 20,
    carbohydrates: 28,
    fiber: 1.8,
    ash: 9.7,
    calcium: 1300,
    phosphorus: 1100,
    sodium: 0.35,
    potassium: 0.75,
    magnesium: 850,
    iron: 120,
    zinc: 0.16,
    copper: 18,
    manganese: 45,
    iodine: 2.1,
    selenium: 0.25,
    vitamin_a: 26000,
    vitamin_d: 1800,
    vitamin_e: 300,
    vitamin_k: 0.8,
    vitamin_b1: 12,
    vitamin_b2: 20,
    vitamin_b6: 8,
    vitamin_b12: 0.1,
    ingredients: 'Свежая курица (26%), дегидрированная курица (14%), рис (14%), овес, куриный жир, свекольная мякоть, таурин, дрожжи, минералы.',
    protein_sources: 'Курица'
  },
  {
    id: 136,
    animal_type: 'собака',
    category: 'терапевтический',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'EXCLUSION',
    name: 'EXCLUSION Diet Hypoallergenic Fish & Potato',
    metabolic_energy: 345.0,
    moisture: 8,
    protein: 22,
    fat: 12,
    carbohydrates: 46,
    fiber: 3.0,
    ash: 9.0,
    calcium: 1000,
    phosphorus: 800,
    sodium: 0.3,
    potassium: 0.6,
    magnesium: 700,
    iron: 150,
    zinc: 0.17,
    copper: 14,
    manganese: 35,
    iodine: 2.0,
    selenium: 0.25,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 250,
    vitamin_k: 0.7,
    vitamin_b1: 15,
    vitamin_b2: 10,
    vitamin_b6: 6,
    vitamin_b12: 0.06,
    ingredients: 'Рыба (25%), картофель (20%), рыбий жир, свекольная мякоть, минералы, витамины, антиоксиданты.',
    protein_sources: 'Рыба'
  },
  {
    id: 137,
    animal_type: 'кошка',
    category: 'терапевтический',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'EXCLUSION',
    name: 'EXCLUSION Diet Hypoallergenic Duck & Potato',
    metabolic_energy: 375.0,
    moisture: 8,
    protein: 30,
    fat: 15,
    carbohydrates: 35,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1000,
    phosphorus: 850,
    sodium: 0.35,
    potassium: 0.7,
    magnesium: 750,
    iron: 140,
    zinc: 0.15,
    copper: 15,
    manganese: 40,
    iodine: 2.2,
    selenium: 0.28,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 250,
    vitamin_k: 0.7,
    vitamin_b1: 15,
    vitamin_b2: 10,
    vitamin_b6: 6,
    vitamin_b12: 0.06,
    ingredients: 'Утка (28%), картофель (22%), утиный жир, свекольная мякоть, таурин, минералы, витамины, антиоксиданты.',
    protein_sources: 'Утка'
  },
  {
    id: 138,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки мелких пород',
    type: 'сухой',
    brand: 'GENESIS',
    name: 'GENESIS Pure Canada My Blue Lake Adult Small Breed',
    metabolic_energy: 380.0,
    moisture: 9,
    protein: 30,
    fat: 18,
    carbohydrates: 32,
    fiber: 3.0,
    ash: 8.0,
    calcium: 1300,
    phosphorus: 1050,
    sodium: 0.25,
    potassium: 0.7,
    magnesium: 900,
    iron: 120,
    zinc: 0.12,
    copper: 16,
    manganese: 35,
    iodine: 1.8,
    selenium: 0.3,
    vitamin_a: 15000,
    vitamin_d: 1800,
    vitamin_e: 220,
    vitamin_k: 0.6,
    vitamin_b1: 15,
    vitamin_b2: 18,
    vitamin_b6: 7,
    vitamin_b12: 0.08,
    ingredients: 'Лосось (25%), сельдь (10%), сладкий картофель, горох, чечевица, куриный жир, яблоки, морковь, шпинат.',
    protein_sources: 'Лосось, Сельдь'
  },
  {
    id: 139,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'GENESIS',
    name: 'GENESIS Pure Canada My Wild Forest Adult Cat',
    metabolic_energy: 400.0,
    moisture: 9,
    protein: 36,
    fat: 20,
    carbohydrates: 25,
    fiber: 2.5,
    ash: 7.5,
    calcium: 1200,
    phosphorus: 1000,
    sodium: 0.3,
    potassium: 0.75,
    magnesium: 800,
    iron: 100,
    zinc: 0.14,
    copper: 14,
    manganese: 40,
    iodine: 2.0,
    selenium: 0.25,
    vitamin_a: 15000,
    vitamin_d: 1800,
    vitamin_e: 220,
    vitamin_k: 0.6,
    vitamin_b1: 15,
    vitamin_b2: 18,
    vitamin_b6: 7,
    vitamin_b12: 0.08,
    ingredients: 'Оленина (20%), кабан (10%), утка (8%), сладкий картофель, горох, чечевица, утиный жир, яблоки, таурин.',
    protein_sources: 'Оленина, Кабан, Утка'
  },
  {
    id: 140,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'влажный',
    brand: 'HILL\'S',
    name: 'HILL\'S Science Diet Adult Beef & Vegetable Stew',
    metabolic_energy: 85.0,
    moisture: 78,
    protein: 4.5,
    fat: 2.8,
    carbohydrates: 12,
    fiber: 1.2,
    ash: 1.5,
    calcium: 180,
    phosphorus: 140,
    sodium: 0.15,
    potassium: 0.25,
    magnesium: 25,
    iron: 15,
    zinc: 0.04,
    copper: 1.2,
    manganese: 2.5,
    iodine: 0.3,
    selenium: 0.05,
    vitamin_a: 2800,
    vitamin_d: 140,
    vitamin_e: 35,
    vitamin_k: 0.12,
    vitamin_b1: 2.8,
    vitamin_b2: 3.2,
    vitamin_b6: 1.8,
    vitamin_b12: 0.015,
    ingredients: 'Говядина, морковь, зеленая фасоль, картофель, рис, куриная печень, кукурузный крахмал, витамины, минералы.',
    protein_sources: 'Говядина, Куриная печень'
  },
  {
    id: 141,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'влажный',
    brand: 'HILL\'S',
    name: 'HILL\'S Science Diet Adult Turkey & Giblets Entree',
    metabolic_energy: 82.0,
    moisture: 78,
    protein: 5.2,
    fat: 2.5,
    carbohydrates: 11,
    fiber: 1.5,
    ash: 2.0,
    calcium: 200,
    phosphorus: 160,
    sodium: 0.18,
    potassium: 0.28,
    magnesium: 30,
    iron: 18,
    zinc: 0.05,
    copper: 1.5,
    manganese: 3.0,
    iodine: 0.4,
    selenium: 0.06,
    vitamin_a: 3200,
    vitamin_d: 160,
    vitamin_e: 40,
    vitamin_k: 0.15,
    vitamin_b1: 3.2,
    vitamin_b2: 3.8,
    vitamin_b6: 2.1,
    vitamin_b12: 0.018,
    ingredients: 'Индейка, потроха индейки, морковь, рис, кукуруза, кукурузный крахмал, таурин, витамины, минералы.',
    protein_sources: 'Индейка, Потроха индейки'
  },
  {
    id: 142,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'JOSERA',
    name: 'JOSERA SensiPlus Adult Sensitive',
    metabolic_energy: 365.0,
    moisture: 10,
    protein: 24,
    fat: 14,
    carbohydrates: 42,
    fiber: 2.8,
    ash: 7.2,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.4,
    potassium: 0.7,
    magnesium: 800,
    iron: 200,
    zinc: 0.15,
    copper: 18,
    manganese: 56,
    iodine: 2.8,
    selenium: 0.35,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 200,
    vitamin_k: 0.8,
    vitamin_b1: 15,
    vitamin_b2: 16,
    vitamin_b6: 20,
    vitamin_b12: 0.1,
    ingredients: 'Утка (16%), рис (15%), картофель (12%), утиный белок, рисовые отруби, свекольная мякоть, утиный жир, минералы.',
    protein_sources: 'Утка'
  },
  {
    id: 143,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'JOSERA',
    name: 'JOSERA Naturelle Adult Cat',
    metabolic_energy: 380.0,
    moisture: 10,
    protein: 30,
    fat: 20,
    carbohydrates: 28,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 800,
    iron: 180,
    zinc: 0.15,
    copper: 18,
    manganese: 50,
    iodine: 2.5,
    selenium: 0.3,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 200,
    vitamin_k: 0.8,
    vitamin_b1: 15,
    vitamin_b2: 16,
    vitamin_b6: 20,
    vitamin_b12: 0.1,
    ingredients: 'Птица (20%), рис (15%), кукуруза, птичий жир, свекольная мякоть, рыбная мука, таурин, минералы.',
    protein_sources: 'Птица, Рыба'
  },
  {
    id: 144,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'щенки мелких пород',
    type: 'сухой',
    brand: 'ADVANCE',
    name: 'ADVANCE Mini Puppy Chicken & Rice',
    metabolic_energy: 395.0,
    moisture: 9,
    protein: 32,
    fat: 20,
    carbohydrates: 28,
    fiber: 2.5,
    ash: 8.5,
    calcium: 1500,
    phosphorus: 1200,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 1100,
    iron: 150,
    zinc: 0.18,
    copper: 20,
    manganese: 50,
    iodine: 2.2,
    selenium: 0.4,
    vitamin_a: 25000,
    vitamin_d: 2000,
    vitamin_e: 350,
    vitamin_k: 1.0,
    vitamin_b1: 20,
    vitamin_b2: 25,
    vitamin_b6: 15,
    vitamin_b12: 0.12,
    ingredients: 'Курица (20%), рис (18%), кукуруза, куриный жир, свекольная мякоть, яичный порошок, рыбий жир, дрожжи.',
    protein_sources: 'Курица, Яйца, Рыба'
  },
  {
    id: 145,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'ADVANCE',
    name: 'ADVANCE Adult Cat Chicken & Rice',
    metabolic_energy: 385.0,
    moisture: 9,
    protein: 37,
    fat: 15,
    carbohydrates: 27,
    fiber: 2.0,
    ash: 10.0,
    calcium: 1100,
    phosphorus: 950,
    sodium: 0.35,
    potassium: 0.75,
    magnesium: 850,
    iron: 140,
    zinc: 0.16,
    copper: 18,
    manganese: 45,
    iodine: 2.8,
    selenium: 0.35,
    vitamin_a: 22000,
    vitamin_d: 1800,
    vitamin_e: 300,
    vitamin_k: 0.9,
    vitamin_b1: 18,
    vitamin_b2: 22,
    vitamin_b6: 12,
    vitamin_b12: 0.1,
    ingredients: 'Курица (22%), рис (20%), кукуруза, куриный жир, свекольная мякоть, таурин, рыбий жир, дрожжи.',
    protein_sources: 'Курица, Рыба'
  },
  {
    id: 146,
    animal_type: 'собака',
    category: 'терапевтический',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'PURINA PRO PLAN',
    name: 'PURINA PRO PLAN Veterinary Diets HA Hypoallergenic',
    metabolic_energy: 375.0,
    moisture: 8,
    protein: 25,
    fat: 12,
    carbohydrates: 45,
    fiber: 2.5,
    ash: 7.5,
    calcium: 1000,
    phosphorus: 800,
    sodium: 0.35,
    potassium: 0.7,
    magnesium: 700,
    iron: 180,
    zinc: 0.2,
    copper: 18,
    manganese: 60,
    iodine: 3.0,
    selenium: 0.35,
    vitamin_a: 20000,
    vitamin_d: 1600,
    vitamin_e: 400,
    vitamin_k: 0.8,
    vitamin_b1: 20,
    vitamin_b2: 25,
    vitamin_b6: 18,
    vitamin_b12: 0.12,
    ingredients: 'Гидролизованный соевый белок, рис, куриный жир, свекольная мякоть, минералы, витамины, антиоксиданты.',
    protein_sources: 'Гидролизованный соевый белок'
  },
  {
    id: 147,
    animal_type: 'кошка',
    category: 'терапевтический',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'PURINA PRO PLAN',
    name: 'PURINA PRO PLAN Veterinary Diets HA Hypoallergenic Cat',
    metabolic_energy: 395.0,
    moisture: 8,
    protein: 35,
    fat: 15,
    carbohydrates: 30,
    fiber: 2.0,
    ash: 10.0,
    calcium: 1000,
    phosphorus: 850,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 750,
    iron: 160,
    zinc: 0.18,
    copper: 16,
    manganese: 55,
    iodine: 2.8,
    selenium: 0.3,
    vitamin_a: 20000,
    vitamin_d: 1600,
    vitamin_e: 400,
    vitamin_k: 0.8,
    vitamin_b1: 20,
    vitamin_b2: 25,
    vitamin_b6: 18,
    vitamin_b12: 0.12,
    ingredients: 'Гидролизованный соевый белок, рис, куриный жир, свекольная мякоть, таурин, минералы, витамины.',
    protein_sources: 'Гидролизованный соевый белок'
  },
  {
    id: 148,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'BELCANDO',
    name: 'BELCANDO Adult Dinner',
    metabolic_energy: 355.0,
    moisture: 9,
    protein: 25,
    fat: 13,
    carbohydrates: 42,
    fiber: 3.5,
    ash: 7.5,
    calcium: 1200,
    phosphorus: 950,
    sodium: 0.3,
    potassium: 0.6,
    magnesium: 800,
    iron: 160,
    zinc: 0.14,
    copper: 16,
    manganese: 45,
    iodine: 2.0,
    selenium: 0.25,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 180,
    vitamin_k: 0.6,
    vitamin_b1: 12,
    vitamin_b2: 14,
    vitamin_b6: 8,
    vitamin_b12: 0.08,
    ingredients: 'Птица (22%), рис, кукуруза, птичий жир, свекольная мякоть, рыбная мука, дрожжи, минералы.',
    protein_sources: 'Птица, Рыба'
  },
  {
    id: 149,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'BELCANDO',
    name: 'BELCANDO Finest Croc',
    metabolic_energy: 390.0,
    moisture: 9,
    protein: 30,
    fat: 20,
    carbohydrates: 29,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.35,
    potassium: 0.75,
    magnesium: 800,
    iron: 150,
    zinc: 0.15,
    copper: 15,
    manganese: 40,
    iodine: 2.5,
    selenium: 0.28,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 180,
    vitamin_k: 0.6,
    vitamin_b1: 12,
    vitamin_b2: 14,
    vitamin_b6: 8,
    vitamin_b12: 0.08,
    ingredients: 'Птица (25%), рис, кукуруза, птичий жир, свекольная мякоть, таурин, рыбная мука, дрожжи.',
    protein_sources: 'Птица, Рыба'
  },
  {
    id: 150,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки крупных пород',
    type: 'сухой',
    brand: 'LEONARDO',
    name: 'LEONARDO Adult Maxi GF Duck',
    metabolic_energy: 350.0,
    moisture: 10,
    protein: 26,
    fat: 12,
    carbohydrates: 42,
    fiber: 3.0,
    ash: 7.0,
    calcium: 1300,
    phosphorus: 1000,
    sodium: 0.3,
    potassium: 0.6,
    magnesium: 900,
    iron: 140,
    zinc: 0.12,
    copper: 14,
    manganese: 35,
    iodine: 1.8,
    selenium: 0.22,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 150,
    vitamin_k: 0.5,
    vitamin_b1: 12,
    vitamin_b2: 15,
    vitamin_b6: 7,
    vitamin_b12: 0.07,
    ingredients: 'Утка (30%), картофель (20%), утиный белок, горох, утиный жир, свекольная мякоть, дрожжи.',
    protein_sources: 'Утка'
  },
  {
    id: 151,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'LEONARDO',
    name: 'LEONARDO Adult Poultry GF',
    metabolic_energy: 385.0,
    moisture: 10,
    protein: 32,
    fat: 20,
    carbohydrates: 26,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.35,
    potassium: 0.75,
    magnesium: 800,
    iron: 130,
    zinc: 0.13,
    copper: 13,
    manganese: 32,
    iodine: 2.0,
    selenium: 0.2,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 150,
    vitamin_k: 0.5,
    vitamin_b1: 12,
    vitamin_b2: 15,
    vitamin_b6: 7,
    vitamin_b12: 0.07,
    ingredients: 'Птица (35%), картофель (20%), птичий белок, горох, птичий жир, свекольная мякоть, таурин.',
    protein_sources: 'Птица'
  },
  {
    id: 152,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'пожилые собаки',
    type: 'сухой',
    brand: 'BOSCH',
    name: 'BOSCH Senior',
    metabolic_energy: 340.0,
    moisture: 9.5,
    protein: 20,
    fat: 8,
    carbohydrates: 52,
    fiber: 4.5,
    ash: 6.0,
    calcium: 1000,
    phosphorus: 750,
    sodium: 0.25,
    potassium: 0.55,
    magnesium: 650,
    iron: 120,
    zinc: 0.12,
    copper: 12,
    manganese: 30,
    iodine: 1.5,
    selenium: 0.2,
    vitamin_a: 15000,
    vitamin_d: 1200,
    vitamin_e: 200,
    vitamin_k: 0.5,
    vitamin_b1: 15,
    vitamin_b2: 12,
    vitamin_b6: 8,
    vitamin_b12: 0.06,
    ingredients: 'Птица (22%), рис, пшеница, кукуруза, птичий жир, свекольная мякоть, рыбная мука, дрожжи.',
    protein_sources: 'Птица, Рыба'
  },
  {
    id: 153,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'пожилые кошки',
    type: 'сухой',
    brand: 'BOSCH',
    name: 'BOSCH Sanabelle Senior',
    metabolic_energy: 365.0,
    moisture: 9.5,
    protein: 28,
    fat: 12,
    carbohydrates: 40,
    fiber: 3.5,
    ash: 7.0,
    calcium: 1000,
    phosphorus: 800,
    sodium: 0.3,
    potassium: 0.7,
    magnesium: 700,
    iron: 110,
    zinc: 0.11,
    copper: 11,
    manganese: 28,
    iodine: 1.8,
    selenium: 0.18,
    vitamin_a: 15000,
    vitamin_d: 1200,
    vitamin_e: 200,
    vitamin_k: 0.5,
    vitamin_b1: 15,
    vitamin_b2: 12,
    vitamin_b6: 8,
    vitamin_b12: 0.06,
    ingredients: 'Птица (25%), рис, пшеница, кукуруза, птичий жир, свекольная мякоть, таурин, рыбная мука.',
    protein_sources: 'Птица, Рыба'
  },
  {
    id: 154,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'NERO GOLD',
    name: 'NERO GOLD Adult 23/13',
    metabolic_energy: 365.0,
    moisture: 10,
    protein: 23,
    fat: 13,
    carbohydrates: 44,
    fiber: 3.0,
    ash: 7.0,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.3,
    potassium: 0.6,
    magnesium: 800,
    iron: 150,
    zinc: 0.13,
    copper: 15,
    manganese: 40,
    iodine: 2.0,
    selenium: 0.25,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 100,
    vitamin_k: 0.5,
    vitamin_b1: 10,
    vitamin_b2: 12,
    vitamin_b6: 6,
    vitamin_b12: 0.05,
    ingredients: 'Курица (18%), рис, кукуруза, пшеница, куриный жир, свекольная мякоть, дрожжи, минералы.',
    protein_sources: 'Курица'
  },
  {
    id: 155,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'NERO GOLD',
    name: 'NERO GOLD Cat Adult',
    metabolic_energy: 385.0,
    moisture: 10,
    protein: 30,
    fat: 16,
    carbohydrates: 32,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1000,
    phosphorus: 850,
    sodium: 0.35,
    potassium: 0.7,
    magnesium: 750,
    iron: 140,
    zinc: 0.14,
    copper: 14,
    manganese: 35,
    iodine: 2.2,
    selenium: 0.22,
    vitamin_a: 15000,
    vitamin_d: 1500,
    vitamin_e: 100,
    vitamin_k: 0.5,
    vitamin_b1: 10,
    vitamin_b2: 12,
    vitamin_b6: 6,
    vitamin_b12: 0.05,
    ingredients: 'Птица (20%), рис, кукуруза, пшеница, птичий жир, свекольная мякоть, таурин, дрожжи.',
    protein_sources: 'Птица'
  },
  {
    id: 156,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'GRANDORF',
    name: 'GRANDORF Adult All Breeds White Fish & Rice',
    metabolic_energy: 370.0,
    moisture: 9,
    protein: 25,
    fat: 13,
    carbohydrates: 42,
    fiber: 3.5,
    ash: 7.5,
    calcium: 1200,
    phosphorus: 950,
    sodium: 0.3,
    potassium: 0.65,
    magnesium: 850,
    iron: 160,
    zinc: 0.14,
    copper: 16,
    manganese: 42,
    iodine: 2.0,
    selenium: 0.28,
    vitamin_a: 18000,
    vitamin_d: 1600,
    vitamin_e: 200,
    vitamin_k: 0.7,
    vitamin_b1: 15,
    vitamin_b2: 18,
    vitamin_b6: 10,
    vitamin_b12: 0.08,
    ingredients: 'Белая рыба (26%), рис (25%), картофель, рыбий жир, свекольная мякоть, дрожжи, минералы.',
    protein_sources: 'Белая рыба'
  },
  {
    id: 157,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'GRANDORF',
    name: 'GRANDORF Adult Indoor White Fish & Rice',
    metabolic_energy: 385.0,
    moisture: 9,
    protein: 32,
    fat: 16,
    carbohydrates: 31,
    fiber: 2.8,
    ash: 9.2,
    calcium: 1100,
    phosphorus: 900,
    sodium: 0.35,
    potassium: 0.75,
    magnesium: 800,
    iron: 150,
    zinc: 0.15,
    copper: 15,
    manganese: 40,
    iodine: 2.2,
    selenium: 0.25,
    vitamin_a: 18000,
    vitamin_d: 1600,
    vitamin_e: 200,
    vitamin_k: 0.7,
    vitamin_b1: 15,
    vitamin_b2: 18,
    vitamin_b6: 10,
    vitamin_b12: 0.08,
    ingredients: 'Белая рыба (28%), рис (22%), картофель, рыбий жир, свекольная мякоть, таурин, дрожжи.',
    protein_sources: 'Белая рыба'
  },
  {
    id: 158,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'щенки всех пород',
    type: 'сухой',
    brand: 'GRANDIN',
    name: 'GRANDIN Puppy Chicken & Rice',
    metabolic_energy: 400.0,
    moisture: 8,
    protein: 30,
    fat: 18,
    carbohydrates: 32,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1500,
    phosphorus: 1200,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 1100,
    iron: 180,
    zinc: 0.18,
    copper: 20,
    manganese: 55,
    iodine: 2.5,
    selenium: 0.4,
    vitamin_a: 25000,
    vitamin_d: 2000,
    vitamin_e: 400,
    vitamin_k: 1.2,
    vitamin_b1: 22,
    vitamin_b2: 28,
    vitamin_b6: 18,
    vitamin_b12: 0.15,
    ingredients: 'Курица (28%), рис (20%), кукуруза, куриный жир, свекольная мякоть, яичный порошок, рыбий жир.',
    protein_sources: 'Курица, Яйца, Рыба'
  },
  {
    id: 159,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'котята',
    type: 'сухой',
    brand: 'GRANDIN',
    name: 'GRANDIN Kitten Chicken & Rice',
    metabolic_energy: 420.0,
    moisture: 8,
    protein: 38,
    fat: 18,
    carbohydrates: 24,
    fiber: 2.0,
    ash: 10.0,
    calcium: 1600,
    phosphorus: 1300,
    sodium: 0.4,
    potassium: 0.85,
    magnesium: 950,
    iron: 160,
    zinc: 0.16,
    copper: 18,
    manganese: 48,
    iodine: 2.8,
    selenium: 0.35,
    vitamin_a: 25000,
    vitamin_d: 2000,
    vitamin_e: 400,
    vitamin_k: 1.2,
    vitamin_b1: 22,
    vitamin_b2: 28,
    vitamin_b6: 18,
    vitamin_b12: 0.15,
    ingredients: 'Курица (30%), рис (18%), кукуруза, куриный жир, свекольная мякоть, таурин, яичный порошок.',
    protein_sources: 'Курица, Яйца'
  },
  {
    id: 160,
    animal_type: 'собака',
    category: 'терапевтический',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'SPECIFIC',
    name: 'SPECIFIC CID Digestive Support',
    metabolic_energy: 350.0,
    moisture: 8,
    protein: 23,
    fat: 8,
    carbohydrates: 55,
    fiber: 4.0,
    ash: 6.0,
    calcium: 900,
    phosphorus: 700,
    sodium: 0.25,
    potassium: 0.6,
    magnesium: 650,
    iron: 140,
    zinc: 0.15,
    copper: 14,
    manganese: 35,
    iodine: 1.8,
    selenium: 0.25,
    vitamin_a: 15000,
    vitamin_d: 1200,
    vitamin_e: 250,
    vitamin_k: 0.6,
    vitamin_b1: 18,
    vitamin_b2: 15,
    vitamin_b6: 12,
    vitamin_b12: 0.08,
    ingredients: 'Рис, куриная мука, кукурузная глютен, куриный жир, свекольная мякоть, рыбий жир, минералы.',
    protein_sources: 'Курица, Рыба'
  },
  {
    id: 161,
    animal_type: 'кошка',
    category: 'терапевтический',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'SPECIFIC',
    name: 'SPECIFIC FID Digestive Support',
    metabolic_energy: 375.0,
    moisture: 8,
    protein: 34,
    fat: 12,
    carbohydrates: 36,
    fiber: 2.5,
    ash: 7.5,
    calcium: 900,
    phosphorus: 750,
    sodium: 0.3,
    potassium: 0.7,
    magnesium: 650,
    iron: 130,
    zinc: 0.13,
    copper: 13,
    manganese: 32,
    iodine: 2.0,
    selenium: 0.2,
    vitamin_a: 15000,
    vitamin_d: 1200,
    vitamin_e: 250,
    vitamin_k: 0.6,
    vitamin_b1: 18,
    vitamin_b2: 15,
    vitamin_b6: 12,
    vitamin_b12: 0.08,
    ingredients: 'Рис, куриная мука, кукурузная глютен, куриный жир, свекольная мякоть, таурин, рыбий жир.',
    protein_sources: 'Курица, Рыба'
  },
  {
    id: 162,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'PREMIUM PLUS',
    name: 'PREMIUM PLUS Adult Chicken & Cereals',
    metabolic_energy: 355.0,
    moisture: 10,
    protein: 22,
    fat: 10,
    carbohydrates: 48,
    fiber: 4.0,
    ash: 6.0,
    calcium: 1000,
    phosphorus: 800,
    sodium: 0.25,
    potassium: 0.55,
    magnesium: 700,
    iron: 120,
    zinc: 0.1,
    copper: 12,
    manganese: 25,
    iodine: 1.5,
    selenium: 0.18,
    vitamin_a: 12000,
    vitamin_d: 1200,
    vitamin_e: 80,
    vitamin_k: 0.4,
    vitamin_b1: 8,
    vitamin_b2: 10,
    vitamin_b6: 5,
    vitamin_b12: 0.04,
    ingredients: 'Курица (18%), пшеница, кукуруза, рис, куриный жир, свекольная мякоть, дрожжи, минералы.',
    protein_sources: 'Курица'
  },
  {
    id: 163,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'PREMIUM PLUS',
    name: 'PREMIUM PLUS Adult Cat Fish',
    metabolic_energy: 375.0,
    moisture: 10,
    protein: 28,
    fat: 12,
    carbohydrates: 38,
    fiber: 3.0,
    ash: 9.0,
    calcium: 1000,
    phosphorus: 850,
    sodium: 0.3,
    potassium: 0.65,
    magnesium: 750,
    iron: 110,
    zinc: 0.11,
    copper: 11,
    manganese: 28,
    iodine: 1.8,
    selenium: 0.18,
    vitamin_a: 12000,
    vitamin_d: 1200,
    vitamin_e: 80,
    vitamin_k: 0.4,
    vitamin_b1: 8,
    vitamin_b2: 10,
    vitamin_b6: 5,
    vitamin_b12: 0.04,
    ingredients: 'Рыба (20%), пшеница, кукуруза, рис, рыбий жир, свекольная мякоть, таурин, дрожжи.',
    protein_sources: 'Рыба'
  },
  {
    id: 164,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки мелких пород',
    type: 'сухой',
    brand: 'SUPERPET',
    name: 'SUPERPET Adult Mini Chicken & Rice',
    metabolic_energy: 385.0,
    moisture: 9,
    protein: 28,
    fat: 16,
    carbohydrates: 35,
    fiber: 3.0,
    ash: 9.0,
    calcium: 1400,
    phosphorus: 1100,
    sodium: 0.35,
    potassium: 0.7,
    magnesium: 1000,
    iron: 150,
    zinc: 0.15,
    copper: 18,
    manganese: 45,
    iodine: 2.2,
    selenium: 0.3,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 200,
    vitamin_k: 0.8,
    vitamin_b1: 16,
    vitamin_b2: 20,
    vitamin_b6: 12,
    vitamin_b12: 0.1,
    ingredients: 'Курица (24%), рис (20%), кукуруза, куриный жир, свекольная мякоть, рыбий жир, дрожжи.',
    protein_sources: 'Курица, Рыба'
  },
  {
    id: 165,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'SUPERPET',
    name: 'SUPERPET Adult Cat Salmon',
    metabolic_energy: 390.0,
    moisture: 9,
    protein: 34,
    fat: 18,
    carbohydrates: 27,
    fiber: 2.5,
    ash: 9.5,
    calcium: 1200,
    phosphorus: 1000,
    sodium: 0.4,
    potassium: 0.8,
    magnesium: 850,
    iron: 140,
    zinc: 0.14,
    copper: 16,
    manganese: 42,
    iodine: 2.5,
    selenium: 0.28,
    vitamin_a: 18000,
    vitamin_d: 1800,
    vitamin_e: 200,
    vitamin_k: 0.8,
    vitamin_b1: 16,
    vitamin_b2: 20,
    vitamin_b6: 12,
    vitamin_b12: 0.1,
    ingredients: 'Лосось (26%), рис (18%), кукуруза, лососевый жир, свекольная мякоть, таурин, дрожжи.',
    protein_sources: 'Лосось'
  },
  {
    id: 166,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'влажный',
    brand: 'ROYAL CANIN',
    name: 'ROYAL CANIN Adult Chunks in Gravy',
    metabolic_energy: 88.0,
    moisture: 79,
    protein: 4.5,
    fat: 2.5,
    carbohydrates: 11.5,
    fiber: 1.3,
    ash: 1.2,
    calcium: 160,
    phosphorus: 120,
    sodium: 0.12,
    potassium: 0.22,
    magnesium: 18,
    iron: 12,
    zinc: 0.035,
    copper: 1.0,
    manganese: 2.0,
    iodine: 0.25,
    selenium: 0.04,
    vitamin_a: 2200,
    vitamin_d: 110,
    vitamin_e: 28,
    vitamin_k: 0.08,
    vitamin_b1: 2.2,
    vitamin_b2: 2.8,
    vitamin_b6: 1.5,
    vitamin_b12: 0.012,
    ingredients: 'Мясо и мясные субпродукты, злаки, минеральные вещества, масла и жиры, витамины.',
    protein_sources: 'Мясо, Субпродукты'
  },
  {
    id: 167,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'влажный',
    brand: 'ROYAL CANIN',
    name: 'ROYAL CANIN Adult Instinctive in Jelly',
    metabolic_energy: 85.0,
    moisture: 79,
    protein: 5.5,
    fat: 2.8,
    carbohydrates: 9.2,
    fiber: 0.8,
    ash: 1.7,
    calcium: 180,
    phosphorus: 140,
    sodium: 0.15,
    potassium: 0.25,
    magnesium: 22,
    iron: 15,
    zinc: 0.04,
    copper: 1.2,
    manganese: 2.5,
    iodine: 0.3,
    selenium: 0.05,
    vitamin_a: 2500,
    vitamin_d: 125,
    vitamin_e: 32,
    vitamin_k: 0.1,
    vitamin_b1: 2.5,
    vitamin_b2: 3.2,
    vitamin_b6: 1.8,
    vitamin_b12: 0.015,
    ingredients: 'Мясо и мясные субпродукты, рыба и рыбные субпродукты, минеральные вещества, таурин.',
    protein_sources: 'Мясо, Субпродукты, Рыба'
  },
  {
    id: 168,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'CHAPPI',
    name: 'CHAPPI Говядина по-домашнему',
    metabolic_energy: 345.0,
    moisture: 10,
    protein: 18,
    fat: 9,
    carbohydrates: 54,
    fiber: 4.0,
    ash: 5.0,
    calcium: 900,
    phosphorus: 700,
    sodium: 0.2,
    potassium: 0.5,
    magnesium: 600,
    iron: 100,
    zinc: 0.08,
    copper: 8,
    manganese: 20,
    iodine: 1.2,
    selenium: 0.15,
    vitamin_a: 10000,
    vitamin_d: 1000,
    vitamin_e: 50,
    vitamin_k: 0.3,
    vitamin_b1: 6,
    vitamin_b2: 8,
    vitamin_b6: 3,
    vitamin_b12: 0.03,
    ingredients: 'Злаки, мясо и мясные субпродукты (говядина 4%), овощи, масла и жиры, витамины, минералы.',
    protein_sources: 'Говядина, Мясные субпродукты'
  },
  {
    id: 169,
    animal_type: 'кошка',
    category: 'повседневный',
    age_group: 'взрослые кошки',
    type: 'сухой',
    brand: 'KITEKAT',
    name: 'KITEKAT Мясной пир',
    metabolic_energy: 365.0,
    moisture: 10,
    protein: 28,
    fat: 9,
    carbohydrates: 44,
    fiber: 4.0,
    ash: 5.0,
    calcium: 900,
    phosphorus: 750,
    sodium: 0.25,
    potassium: 0.6,
    magnesium: 650,
    iron: 90,
    zinc: 0.09,
    copper: 9,
    manganese: 22,
    iodine: 1.5,
    selenium: 0.15,
    vitamin_a: 10000,
    vitamin_d: 1000,
    vitamin_e: 50,
    vitamin_k: 0.3,
    vitamin_b1: 6,
    vitamin_b2: 8,
    vitamin_b6: 3,
    vitamin_b12: 0.03,
    ingredients: 'Злаки, мясо и мясные субпродукты, рыба и рыбные субпродукты, масла и жиры, таурин.',
    protein_sources: 'Мясо, Субпродукты, Рыба'
  },
  {
    id: 170,
    animal_type: 'собака',
    category: 'повседневный',
    age_group: 'взрослые собаки',
    type: 'сухой',
    brand: 'DARLING',
    name: 'DARLING С курицей и овощами',
    metabolic_energy: 350.0,
    moisture: 10,
    protein: 20,
    fat: 8,
    carbohydrates: 52,
    fiber: 4.5,
    ash: 5.5,
    calcium: 950,
    phosphorus: 750,
    sodium: 0.22,
    potassium: 0.52,
    magnesium: 650,
    iron: 110,
    zinc: 0.09,
    copper: 9,
    manganese: 22,
    iodine: 1.3,
    selenium: 0.16,
    vitamin_a: 11000,
    vitamin_d: 1100,
    vitamin_e: 55,
    vitamin_k: 0.35,
    vitamin_b1: 7,
    vitamin_b2: 9,
    vitamin_b6: 4,
    vitamin_b12: 0.035,
    ingredients: 'Злаки, мясо и мясные субпродукты (курица 4%), овощи (морковь, горох), масла и жиры.',
    protein_sources: 'Курица, Мясные субпродукты'
  }
];
];

function normalizeAnimalType(type) {
  const animalTypes = {
    'собака': 'dog',
    'кошка': 'cat',
    'dog': 'dog',
    'cat': 'cat'
  };
  return animalTypes[type.toLowerCase()] || 'dog';
}

function normalizeCategory(category) {
  const categories = {
    'терапевтический': 'diet',
    'повседневный': 'adult',
    'лечебный': 'diet',
    'щенки': 'puppy_medium',
    'котята': 'kitten',
    'пожилые': 'senior',
    'взрослые': 'adult'
  };
  return categories[category.toLowerCase()] || 'adult';
}

function normalizeFeedType(type) {
  const feedTypes = {
    'сухой': 'dry',
    'влажный': 'wet',
    'консервы': 'wet',
    'лакомства': 'treats'
  };
  return feedTypes[type.toLowerCase()] || 'dry';
}

async function importFeeds() {
  console.log('Начинаю импорт кормов...');
  
  try {
    const db = getDatabase();
    
    // Создаем таблицу feeds если её нет
    await new Promise((resolve, reject) => {
      db.run(`
        CREATE TABLE IF NOT EXISTS feeds (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          user_id INTEGER NULL,
          name TEXT NOT NULL,
          brand TEXT NOT NULL,
          type TEXT NOT NULL CHECK (type IN ('dry', 'wet', 'raw', 'treats')),
          animal_type TEXT NOT NULL CHECK (animal_type IN ('dog', 'cat', 'both')),
          category TEXT NOT NULL CHECK (category IN ('kitten', 'puppy_small', 'puppy_medium', 'puppy_large', 'adult', 'senior', 'weight_loss', 'diet', 'special')),
          metabolic_energy REAL NOT NULL,
          protein REAL,
          fat REAL,
          carbohydrates REAL,
          fiber REAL,
          ash REAL,
          moisture REAL,
          calcium INTEGER,
          phosphorus INTEGER,
          sodium INTEGER,
          potassium INTEGER,
          magnesium INTEGER,
          iron INTEGER,
          zinc INTEGER,
          copper INTEGER,
          manganese INTEGER,
          selenium REAL,
          iodine INTEGER,
          vitamin_a INTEGER,
          vitamin_d INTEGER,
          vitamin_e INTEGER,
          vitamin_k INTEGER,
          vitamin_b1 REAL,
          vitamin_b2 REAL,
          vitamin_b3 REAL,
          vitamin_b5 REAL,
          vitamin_b6 REAL,
          vitamin_b7 REAL,
          vitamin_b9 REAL,
          vitamin_b12 REAL,
          vitamin_c INTEGER,
          ingredients TEXT,
          notes TEXT,
          price_per_kg REAL,
          is_available BOOLEAN DEFAULT 1,
          is_public BOOLEAN DEFAULT 1,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `, (err) => {
        if (err) reject(err);
        else resolve();
      });
    });
    
    let imported = 0;
    let skipped = 0;
    
    for (const feed of feedsData) {
      try {
        // Проверяем, существует ли корм с таким названием
        const existing = await new Promise((resolve, reject) => {
          db.get('SELECT id FROM feeds WHERE name = ? AND brand = ?', [feed.name, feed.brand], (err, row) => {
            if (err) reject(err);
            else resolve(row);
          });
        });
        
        if (existing) {
          console.log(`Корм "${feed.name}" уже существует, пропускаю...`);
          skipped++;
          continue;
        }
        
        // Добавляем новый корм
        await new Promise((resolve, reject) => {
          const query = `
            INSERT INTO feeds (
              name, brand, type, animal_type, category, metabolic_energy,
              protein, fat, carbohydrates, fiber, ash, moisture,
              calcium, phosphorus, sodium, potassium, magnesium, iron, zinc, copper, manganese,
              selenium, iodine, vitamin_a, vitamin_d, vitamin_e, vitamin_k,
              vitamin_b1, vitamin_b2, vitamin_b6, vitamin_b12, ingredients, notes, is_public
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
          `;
          
          const params = [
            feed.name,
            feed.brand,
            normalizeFeedType(feed.type),
            normalizeAnimalType(feed.animal_type),
            normalizeCategory(feed.category),
            feed.metabolic_energy / 10, // Конвертируем в ккал/100г (было в ккал/кг)
            feed.protein,
            feed.fat,
            feed.carbohydrates,
            feed.fiber,
            feed.ash,
            feed.moisture,
            Math.round(feed.calcium || 0),
            Math.round(feed.phosphorus || 0),
            Math.round((feed.sodium || 0) * 1000), // конвертируем в мг
            Math.round((feed.potassium || 0) * 1000), // конвертируем в мг
            Math.round(feed.magnesium || 0),
            Math.round(feed.iron || 0),
            Math.round((feed.zinc || 0) * 1000), // конвертируем в мг
            Math.round(feed.copper || 0),
            Math.round(feed.manganese || 0),
            feed.selenium,
            Math.round(feed.iodine || 0),
            Math.round(feed.vitamin_a || 0),
            Math.round(feed.vitamin_d || 0),
            Math.round(feed.vitamin_e || 0),
            feed.vitamin_k,
            feed.vitamin_b1,
            feed.vitamin_b2,
            feed.vitamin_b6,
            feed.vitamin_b12,
            feed.ingredients,
            `Источники белка: ${feed.protein_sources || 'Не указано'}. Возрастная группа: ${feed.age_group}`,
            1 // is_public
          ];
          
          db.run(query, params, function(err) {
            if (err) {
              console.error(`Ошибка при добавлении корма "${feed.name}":`, err);
              reject(err);
            } else {
              console.log(`✓ Добавлен корм: ${feed.brand} - ${feed.name}`);
              imported++;
              resolve();
            }
          });
        });
        
      } catch (error) {
        console.error(`Ошибка при обработке корма "${feed.name}":`, error);
      }
    }
    
    console.log(`\n🎉 Импорт завершен!`);
    console.log(`📊 Статистика:`);
    console.log(`   ✓ Импортировано: ${imported} кормов`);
    console.log(`   ⚠ Пропущено: ${skipped} кормов`);
    
    // Показываем общее количество кормов в базе
    const totalCount = await new Promise((resolve, reject) => {
      db.get('SELECT COUNT(*) as count FROM feeds', (err, row) => {
        if (err) reject(err);
        else resolve(row.count);
      });
    });
    
    console.log(`   📚 Всего кормов в базе: ${totalCount}`);
    
  } catch (error) {
    console.error('Ошибка при импорте:', error);
  }
  
  process.exit(0);
}

// Запускаем импорт
if (require.main === module) {
  importFeeds();
}

module.exports = { importFeeds }; 